// it's important to add prefix /react in import below
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { IMovieSearch, IMovieSearchResponse } from "../../models/models";

export const tmdbApi = createApi({
  reducerPath: "tmdb/api",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://api.themoviedb.org/3/",
  }),
  endpoints: (build) => ({
    // [*]
    // <T, Q>: T - what will be returned; Q - type of param that'll be provided by us
    searchMovie: build.query<IMovieSearch[], string>({
      query: (term: string) => ({
        url: `search/movie`,
        params: {
          query: term,
          api_key: "e53afc585bcc1648f859c0ff148012ea",
        },
      }),
      transformResponse: (response: IMovieSearchResponse<IMovieSearch>) =>
        response.results,
    }),
  }),
});

// useSearchMultiQuery - name that automatically generated by toolkit [*]
// 'SerachMulti' - method name in 'endpoints' callback that we choose
// 'Query' - build method
export const { useSearchMovieQuery } = tmdbApi;
